version: "3"
services:
  web:
    image: mcr.microsoft.com/dotnet/core/sdk:3.1
    volumes:
      - ./:/app
    working_dir: /app
    entrypoint: "dotnet run --project /app/Users.API/"
    ports:
      - "5000:5000"
      - "5001:5001"
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always        
    environment:
       MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql:/var/lib/mysql
      - ./Users.Infrastructure/sql/:/data/application/
volumes: 
  mysql:

