version: "3"
services:
  web:
    build: "mcr.microsoft.com/dotnet/core/aspnet:3.1"
    ports:
      - "8000:80"
    depends_on:
      - db
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root

